// Auto-generated from data/team_player.json
export const PLAYER_TO_TEAM: Record<string, string> = {
  "Brenden Aaronson": "Leeds United",
  "Zach Abbott": "Nottingham Forest",
  "Joshua Acheampong": "Chelsea",
  "Tyler Adams": "Bournemouth",
  "Tosin Adarabioyo": "Chelsea",
  "Simon Adingra": "Sunderland",
  "Amine Adli": "Bournemouth",
  "Emmanuel Agbadou": "Wolves",
  "Nayef Aguerd": "West Ham United",
  "Ola Aina": "Nottingham Forest",
  "Rayan Aït-Nouri": "Manchester City",
  "Kristoffer Ajer": "Brentford",
  "Nathan Aké": "Manchester City",
  "Carlos Alcaraz": "Everton",
  "Omar Alderete": "Sunderland",
  "Alisson": "Liverpool",
  "Max Alleyne": "Manchester City",
  "Jaydon Amauri Banel": "Burnley",
  "Ethan Ampadu": "Leeds United",
  "Joachim Andersen": "Fulham",
  "Elliot Anderson": "Nottingham Forest",
  "André": "Wolves",
  "Jaidon Anthony": "Burnley",
  "Alphonse Areola": "West Ham United",
  "Jhon Arias": "Wolves",
  "Harrison Armstrong": "Everton",
  "Tolu Arokodare": "Wolves",
  "Taiwo Awoniyi": "Nottingham Forest",
  "Yasin Ayari": "Brighton",
  "Benoît Badiashile": "Chelsea",
  "Dilane Bakwa": "Nottingham Forest",
  "Carlos Baleba": "Brighton",
  "Daniel Ballard": "Sunderland",
  "Ross Barkley": "Aston Villa",
  "Ashley Barnes": "Burnley",
  "Harvey Barnes": "Newcastle United",
  "Thierno Barry": "Everton",
  "Calvin Bassey": "Fulham",
  "Altay Bayındır": "Manchester Utd",
  "Jean-Ricner Bellegarde": "Wolves",
  "Rodrigo Bentancur": "Tottenham Hotspur",
  "Sander Berge": "Fulham",
  "Lucas Bergvall": "Tottenham Hotspur",
  "Beto": "Everton",
  "Jaka Bijol": "Leeds United",
  "Yves Bissouma": "Tottenham Hotspur",
  "Marco Bizot": "Aston Villa",
  "Oscar Bobb": "Manchester City",
  "Lamare Bogarde": "Aston Villa",
  "Jayden Bogle": "Leeds United",
  "Sebastiaan Bornauw": "Leeds United",
  "Olivier Boscagli": "Brighton",
  "Sven Botman": "Newcastle United",
  "Jarrod Bowen": "West Ham United",
  "Conor Bradley": "Liverpool",
  "Brian Brobbey": "Sunderland",
  "Armando Broja": "Burnley",
  "David Brooks": "Bournemouth",
  "Jacob Bruun Larsen": "Burnley",
  "Emi Buendía": "Aston Villa",
  "Hugo Bueno": "Wolves",
  "Santiago Bueno": "Wolves",
  "Facundo Buonanotte": "Chelsea",
  "Dan Burn": "Newcastle United",
  "Bradley Burrowes": "Aston Villa",
  "Sam Byram": "Leeds United",
  "Moisés Caicedo": "Chelsea",
  "Tom Cairney": "Fulham",
  "Riccardo Calafiori": "Arsenal",
  "Dominic Calvert-Lewin": "Leeds United",
  "Jaydee Canvot": "Crystal Palace",
  "Fabio Carvalho": "Brentford",
  "Casemiro": "Manchester Utd",
  "Matty Cash": "Aston Villa",
  "Timothy Castagne": "Fulham",
  "Valentín Castellanos": "West Ham United",
  "Trevoh Chalobah": "Chelsea",
  "Rayan Cherki": "Manchester City",
  "Federico Chiesa": "Liverpool",
  "Tawanda Chirewa": "Wolves",
  "Ryan Christie": "Bournemouth",
  "Samuel Chukwueze": "Fulham",
  "Dennis Cirkin": "Sunderland",
  "Nathaniel Clyne": "Crystal Palace",
  "Séamus Coleman": "Everton",
  "Nathan Collins": "Brentford",
  "Lewis Cook": "Bournemouth",
  "Diego Coppola": "Brighton",
  "Marc Cucurella": "Chelsea",
  "Jorge Cuenca": "Fulham",
  "Josh Cullen": "Burnley",
  "Jair Cunha": "Nottingham Forest",
  "Matheus Cunha": "Manchester Utd",
  "Diogo Dalot": "Manchester Utd",
  "Mikkel Damsgaard": "Brentford",
  "Kevin Danso": "Tottenham Hotspur",
  "Karl Darlow": "Leeds United",
  "Ben Davies": "Tottenham Hotspur",
  "Maxim De Cuyper": "Brighton",
  "Liam Delap": "Chelsea",
  "Sepp van den Berg": "Brentford",
  "Justin Devenny": "Crystal Palace",
  "Kiernan Dewsbury-Hall": "Everton",
  "Bafodé Diakité": "Bournemouth",
  "Amad Diallo": "Manchester Utd",
  "Habib Diarra": "Sunderland",
  "Rúben Dias": "Manchester City",
  "Tyler Dibling": "Everton",
  "Lucas Digne": "Aston Villa",
  "Issa Diop": "Fulham",
  "El Hadji Malick Diouf": "West Ham United",
  "Matt Doherty": "Wolves",
  "Jeremy Doku": "Manchester City",
  "Nicolás Domínguez": "Nottingham Forest",
  "Gianluigi Donnarumma": "Manchester City",
  "Romelle Donovan": "Brentford",
  "Patrick Dorgu": "Manchester Utd",
  "Max Dowman": "Arsenal",
  "Radu Drăgușin": "Tottenham Hotspur",
  "Joél Drakes-Thomas": "Crystal Palace",
  "Martin Dúbravka": "Burnley",
  "Lewis Dunk": "Brighton",
  "George Earthy": "West Ham United",
  "Odsonne Édouard": "Crystal Palace",
  "Marcus Edwards": "Burnley",
  "Hjalmar Ekdal": "Burnley",
  "Hugo Ekitike": "Liverpool",
  "Anthony Elanga": "Newcastle United",
  "Harvey Elliott": "Aston Villa",
  "Wataru Endo": "Liverpool",
  "Romain Esse": "Crystal Palace",
  "Maxime Estève": "Burnley",
  "Evanilson": "Bournemouth",
  "Eberechi Eze": "Crystal Palace",
  "Bruno Fernandes": "Manchester Utd",
  "Mateus Fernandes": "West Ham United",
  "Enzo Fernández": "Chelsea",
  "Zian Flemming": "Burnley",
  "Jack Fletcher": "Manchester Utd",
  "Phil Foden": "Manchester City",
  "Wesley Fofana": "Chelsea",
  "Lyle Foster": "Burnley",
  "Tyler Fredricson": "Manchester Utd",
  "Jeremie Frimpong": "Liverpool",
  "Niclas Füllkrug": "West Ham United",
  "Cody Gakpo": "Liverpool",
  "Conor Gallagher": "Tottenham Hotspur",
  "Idrissa Gana Gueye": "Everton",
  "Ben Gannon-Doak": "Bournemouth",
  "Andrés García": "Aston Villa",
  "Alejandro Garnacho": "Chelsea",
  "James Garner": "Everton",
  "Lutsharel Geertruida": "Sunderland",
  "Tyrique George": "Chelsea",
  "Morgan Gibbs-White": "Nottingham Forest",
  "Jamie Gittens": "Chelsea",
  "Wilfried Gnonto": "Leeds United",
  "João Gomes": "Wolves",
  "Rodrigo Gomes": "Wolves",
  "Toti Gomes": "Wolves",
  "Diego Gómez": "Brighton",
  "Joe Gomez": "Liverpool",
  "Nicolás González": "Manchester City",
  "Anthony Gordon": "Newcastle United",
  "Ryan Gravenberch": "Liverpool",
  "Archie Gray": "Tottenham Hotspur",
  "Jack Grealish": "Everton",
  "Pascal Groß": "Brighton",
  "Brajan Gruda": "Brighton",
  "Ilia Gruev": "Leeds United",
  "Gabriel Gudmundsson": "Leeds United",
  "Marc Guéhi": "Crystal Palace",
  "Evann Guessand": "Aston Villa",
  "Luis Guilherme": "West Ham United",
  "Bruno Guimarães": "Newcastle United",
  "Marc Guiu": "Chelsea",
  "Malo Gusto": "Chelsea",
  "Joško Gvardiol": "Manchester City",
  "Viktor Gyökeres": "Arsenal",
  "Erling Haaland": "Manchester City",
  "Lewis Hall": "Newcastle United",
  "Jack Harrison": "Leeds United",
  "Quilindschy Hartman": "Burnley",
  "Jorrel Hato": "Chelsea",
  "Kai Havertz": "Arsenal",
  "Ayden Heaven": "Manchester Utd",
  "Jan Paul van Hecke": "Brighton",
  "Hwang Hee-chan": "Wolves",
  "George Hemmings": "Aston Villa",
  "Dean Henderson": "Crystal Palace",
  "Jordan Henderson": "Brentford",
  "Rico Henry": "Brentford",
  "Mads Hermansen": "West Ham United",
  "Aaron Hickey": "Brentford",
  "James Hill": "Bournemouth",
  "Piero Hincapié": "Arsenal",
  "Jack Hinshelwood": "Brighton",
  "Ki-Jana Hoever": "Wolves",
  "Callum Hudson-Odoi": "Nottingham Forest",
  "Will Hughes": "Crystal Palace",
  "Trai Hume": "Sunderland",
  "Bashir Humphreys": "Burnley",
  "Omari Hutchinson": "Nottingham Forest",
  "Igor": "West Ham United",
  "Tim Iroegbunam": "Everton",
  "Andy Irving": "West Ham United",
  "Alexander Isak": "Liverpool",
  "Wilson Isidor": "Sunderland",
  "Alex Iwobi": "Fulham",
  "Daniel James": "Leeds United",
  "Reece James": "Chelsea",
  "Vitaly Janelt": "Brentford",
  "Mathias Jensen": "Brentford",
  "Gabriel Jesus": "Arsenal",
  "Igor Jesus": "Nottingham Forest",
  "Álex Jiménez": "Bournemouth",
  "Raúl Jiménez": "Fulham",
  "Jamaldeen Jimoh": "Aston Villa",
  "João Pedro": "Chelsea",
  "Joelinton": "Newcastle United",
  "John": "Nottingham Forest",
  "Brennan Johnson": "Crystal Palace",
  "Sam Johnstone": "Wolves",
  "Curtis Jones": "Liverpool",
  "Eli Junior Kroupi": "Bournemouth",
  "Hamed Junior Traorè": "Bournemouth",
  "James Justin": "Leeds United",
  "Filip Jørgensen": "Chelsea",
  "Ferdi Kadioglu": "Brighton",
  "Sasa Kalajdzic": "Wolves",
  "Arnaud Kalimuendo": "Nottingham Forest",
  "Daichi Kamada": "Crystal Palace",
  "Boubacar Kamara": "Aston Villa",
  "Mohamadou Kanté": "West Ham United",
  "Michael Kayode": "Brentford",
  "Michael Keane": "Everton",
  "Caoimhín Kelleher": "Brentford",
  "Milos Kerkez": "Liverpool",
  "Kevin": "Fulham",
  "Abdukodir Khusanov": "Manchester City",
  "Max Kilman": "West Ham United",
  "Joshua King": "Fulham",
  "Justin Kluivert": "Bournemouth",
  "Joe Knight": "Brighton",
  "Randal Kolo Muani": "Tottenham Hotspur",
  "Ibrahima Konaté": "Liverpool",
  "Ezri Konsa": "Aston Villa",
  "Charalampos Kostoulas": "Brighton",
  "Mateo Kovačić": "Manchester City",
  "Emil Krafth": "Newcastle United",
  "Ladislav Krejčí": "Wolves",
  "Mohammed Kudus": "Tottenham Hotspur",
  "Jonah Kusi-Asare": "Fulham",
  "Shea Lacey": "Manchester Utd",
  "Maxence Lacroix": "Crystal Palace",
  "Senne Lammens": "Manchester Utd",
  "Jamaal Lascelles": "Newcastle United",
  "Josh Laurent": "Burnley",
  "Roméo Lavia": "Chelsea",
  "Enzo Le Fée": "Sunderland",
  "Bernd Leno": "Fulham",
  "Jefferson Lerma": "Crystal Palace",
  "Rico Lewis": "Manchester City",
  "Keane Lewis-Potter": "Brentford",
  "Myles Lewis-Skelly": "Arsenal",
  "Matthijs de Ligt": "Manchester Utd",
  "Pedro Lima": "Wolves",
  "Victor Lindelöf": "Aston Villa",
  "Valentino Livramento": "Newcastle United",
  "Sean Longstaff": "Leeds United",
  "Fer López": "Wolves",
  "Lucas": "Burnley",
  "Florentino Luís": "Burnley",
  "Douglas Luiz": "Nottingham Forest",
  "Saša Lukić": "Fulham",
  "Ian Maatsen": "Aston Villa",
  "Alexis Mac Allister": "Liverpool",
  "Noni Madueke": "Arsenal",
  "Gabriel Magalhães": "Arsenal",
  "Soungoutou Magassa": "West Ham United",
  "Harry Maguire": "Manchester Utd",
  "Kobbie Mainoo": "Manchester Utd",
  "Tyrell Malacia": "Manchester Utd",
  "Donyell Malen": "Aston Villa",
  "Giorgi Mamardashvili": "Liverpool",
  "Reinildo Mandava": "Sunderland",
  "Mateus Mane": "Wolves",
  "Bendito Mantato": "Manchester Utd",
  "Omar Marmoush": "Manchester City",
  "Callum Marshall": "West Ham United",
  "Gabriel Martinelli": "Arsenal",
  "Emiliano Martínez": "Aston Villa",
  "Lisandro Martínez": "Manchester Utd",
  "Arthur Masuaku": "Sunderland",
  "Pape Matar Sarr": "Tottenham Hotspur",
  "Jean-Philippe Mateta": "Crystal Palace",
  "Konstantinos Mavropanos": "West Ham United",
  "Eliezer Mayenda": "Sunderland",
  "Ezra Mayers": "West Ham United",
  "Noussair Mazraoui": "Manchester Utd",
  "Bryan Mbeumo": "Manchester Utd",
  "James Mcatee": "Nottingham Forest",
  "John McGinn": "Aston Villa",
  "Dwight McNeil": "Everton",
  "Hannibal Mejbri": "Burnley",
  "Mikel Merino": "Arsenal",
  "Antoni Milambo": "Brentford",
  "Nikola Milenković": "Nottingham Forest",
  "Lewis Miley": "Newcastle United",
  "James Milner": "Brighton",
  "Veljko Milosavljević": "Bournemouth",
  "Tyrone Mings": "Aston Villa",
  "Yankuba Minteh": "Brighton",
  "Tyrick Mitchell": "Crystal Palace",
  "Kaoru Mitoma": "Brighton",
  "Morato": "Nottingham Forest",
  "Cristhian Mosquera": "Arsenal",
  "Yerson Mosquera": "Wolves",
  "Mason Mount": "Manchester Utd",
  "Divine Mukasa": "Manchester City",
  "Nordi Mukiele": "Sunderland",
  "Romaine Mundle": "Sunderland",
  "Marshall Munetsi": "Wolves",
  "Rodrigo Muniz": "Fulham",
  "Daniel Muñoz": "Crystal Palace",
  "Murillo": "Nottingham Forest",
  "Jacob Murphy": "Newcastle United",
  "Vitaliy Mykolenko": "Everton",
  "David Møller Wolfe": "Wolves",
  "Iliman Ndiaye": "Everton",
  "Dan Ndoye": "Nottingham Forest",
  "Dan Neil": "Sunderland",
  "Reiss Nelson": "Brentford",
  "Pedro Neto": "Chelsea",
  "Rio Ngumoha": "Liverpool",
  "Eddie Nketiah": "Crystal Palace",
  "Lukas Nmecha": "Leeds United",
  "Matheus Nunes": "Manchester City",
  "Ethan Nwaneri": "Arsenal",
  "Trey Nyoni": "Liverpool",
  "Christian Nørgaard": "Arsenal",
  "Jake O'Brien": "Everton",
  "Luke O'Nien": "Sunderland",
  "Matt O'Riley": "Brighton",
  "Wilson Odobert": "Tottenham Hotspur",
  "Noah Okafor": "Leeds United",
  "Amadou Onana": "Aston Villa",
  "Frank Onyeka": "Brentford",
  "Nehemiah Oriola": "Brighton",
  "William Osula": "Newcastle United",
  "Dango Ouattara": "Brentford",
  "Nico O’Reilly": "Manchester City",
  "Pablo": "West Ham United",
  "João Palhinha": "Tottenham Hotspur",
  "Cole Palmer": "Chelsea",
  "Lucas Paquetá": "West Ham United",
  "Nathan Patterson": "Everton",
  "Myles Peart-Harris": "Brentford",
  "Lucas Perri": "Leeds United",
  "Đorđe Petrović": "Bournemouth",
  "Jordan Pickford": "Everton",
  "Ethan Pinnock": "Brentford",
  "Yeremi Pino": "Crystal Palace",
  "Joël Piroe": "Leeds United",
  "Nick Pope": "Newcastle United",
  "Pedro Porro": "Tottenham Hotspur",
  "Freddie Potts": "West Ham United",
  "Aaron Ramsdale": "Newcastle United",
  "Jacob Ramsey": "Newcastle United",
  "David Raya": "Arsenal",
  "Harrison Reed": "Fulham",
  "Tijjani Reijnders": "Manchester City",
  "Declan Rice": "Arsenal",
  "Chris Richards": "Crystal Palace",
  "Richarlison": "Tottenham Hotspur",
  "Chris Rigg": "Sunderland",
  "Patrick Roberts": "Sunderland",
  "Andrew Robertson": "Liverpool",
  "Antonee Robinson": "Fulham",
  "Kaden Rodney": "Crystal Palace",
  "Joe Rodon": "Leeds United",
  "Rodri": "Manchester City",
  "Guido Rodríguez": "West Ham United",
  "Robin Roefs": "Sunderland",
  "Morgan Rogers": "Aston Villa",
  "Merlin Röhl": "Everton",
  "Cristian Romero": "Tottenham Hotspur",
  "Georginio Rutter": "Brighton",
  "José Sá": "Wolves",
  "Noah Sadiki": "Sunderland",
  "Bukayo Saka": "Arsenal",
  "Mohamed Salah": "Liverpool",
  "William Saliba": "Arsenal",
  "Robert Sánchez": "Chelsea",
  "Jadon Sancho": "Aston Villa",
  "Ibrahim Sangaré": "Nottingham Forest",
  "Andrey Santos": "Chelsea",
  "Ismaila Sarr": "Crystal Palace",
  "Sávio": "Manchester City",
  "Nicolò Savona": "Nottingham Forest",
  "Oliver Scarles": "West Ham United",
  "Dane Scarlett": "Tottenham Hotspur",
  "Kevin Schade": "Brentford",
  "Fabian Schär": "Newcastle United",
  "Alex Scott": "Bournemouth",
  "Jenson Seelt": "Sunderland",
  "Matz Sels": "Nottingham Forest",
  "Antoine Semenyo": "Manchester City",
  "Marcos Senesi": "Bournemouth",
  "Benjamin Šeško": "Manchester Utd",
  "Ryan Sessegnon": "Fulham",
  "Luke Shaw": "Manchester Utd",
  "Bernardo Silva": "Manchester City",
  "Jota Silva": "Nottingham Forest",
  "Xavi Simons": "Tottenham Hotspur",
  "Adam Smith": "Bournemouth",
  "Emile Smith Rowe": "Fulham",
  "Dominic Solanke": "Tottenham Hotspur",
  "Julio Soler": "Bournemouth",
  "Oliver Sonne": "Burnley",
  "Borna Sosa": "Crystal Palace",
  "Tomáš Souček": "West Ham United",
  "Djed Spence": "Tottenham Hotspur",
  "Anton Stach": "Leeds United",
  "John Stones": "Manchester City",
  "Jørgen Strand Larsen": "Wolves",
  "Pascal Struijk": "Leeds United",
  "Crysencio Summerville": "West Ham United",
  "Dominik Szoboszlai": "Liverpool",
  "Chemsdine Talbi": "Sunderland",
  "Ao Tanaka": "Leeds United",
  "James Tarkowski": "Everton",
  "Marcus Tavernier": "Bournemouth",
  "Loum Tchaouna": "Burnley",
  "Jackson Tchatchoua": "Wolves",
  "Mathys Tel": "Tottenham Hotspur",
  "Kenny Tete": "Fulham",
  "Thiago": "Brentford",
  "Malick Thiaw": "Newcastle United",
  "Youri Tielemans": "Aston Villa",
  "Jurriën Timber": "Arsenal",
  "Jean-Clair Todibo": "West Ham United",
  "Sandro Tonali": "Newcastle United",
  "Pau Torres": "Aston Villa",
  "James Trafford": "Manchester City",
  "Adama Traoré": "Fulham",
  "Bertrand Traoré": "Sunderland",
  "Mike Trésor": "Burnley",
  "Kieran Trippier": "Newcastle United",
  "Leandro Trossard": "Arsenal",
  "Adrien Truffert": "Bournemouth",
  "Axel Tuanzebe": "Burnley",
  "Stefanos Tzimas": "Brighton",
  "Christantus Uche": "Crystal Palace",
  "Destiny Udogie": "Tottenham Hotspur",
  "Manuel Ugarte": "Manchester Utd",
  "Lesley Ugochukwu": "Burnley",
  "Enes Ünal": "Bournemouth",
  "Virgil van Dijk": "Liverpool",
  "Joël Veltman": "Brighton",
  "Micky van de Ven": "Tottenham Hotspur",
  "Bart Verbruggen": "Brighton",
  "Guglielmo Vicario": "Tottenham Hotspur",
  "Kyle Walker": "Burnley",
  "Kyle Walker-Peters": "West Ham United",
  "Aaron Wan-Bissaka": "West Ham United",
  "James Ward-Prowse": "West Ham United",
  "Ollie Watkins": "Aston Villa",
  "Tom Watson": "Brighton",
  "Danny Welbeck": "Brighton",
  "Adam Wharton": "Crystal Palace",
  "Ben White": "Arsenal",
  "Mats Wieffer": "Brighton",
  "Neco Williams": "Nottingham Forest",
  "Estêvão Willian": "Chelsea",
  "Joe Willock": "Newcastle United",
  "Callum Wilson": "West Ham United",
  "Harry Wilson": "Fulham",
  "Ben Winterburn": "Bournemouth",
  "Florian Wirtz": "Liverpool",
  "Yoane Wissa": "Newcastle United",
  "Nick Woltemade": "Newcastle United",
  "Chris Wood": "Nottingham Forest",
  "Joe Worrall": "Burnley",
  "Granit Xhaka": "Sunderland",
  "Yehor Yarmoliuk": "Brentford",
  "Ryan Yates": "Nottingham Forest",
  "Leny Yoro": "Manchester Utd",
  "Oleksandr Zinchenko": "Nottingham Forest",
  "Joshua Zirkzee": "Manchester Utd",
  "Martín Zubimendi": "Arsenal",
  "Martin Ødegaard": "Arsenal"
};
